FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    python3-pip \
    ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    pymodbus \
    pyserial
